// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOeLpqahxWh1Wmn4J-kuyNV_gDQUsVHwM',
    appId: '1:666731394983:web:b9ec6f2d0fdfdd713ba882',
    messagingSenderId: '666731394983',
    projectId: 'austmart-2b349',
    authDomain: 'austmart-2b349.firebaseapp.com',
    storageBucket: 'austmart-2b349.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHqDxCTy3g-J-kM9az6-GIrYZsyrfpfw4',
    appId: '1:666731394983:android:7b2d52343bcd813f3ba882',
    messagingSenderId: '666731394983',
    projectId: 'austmart-2b349',
    storageBucket: 'austmart-2b349.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXetSlXgyv-5hQ3AqAD5SgJ8BB3pmzz0s',
    appId: '1:666731394983:ios:2e1e7a3597de18113ba882',
    messagingSenderId: '666731394983',
    projectId: 'austmart-2b349',
    storageBucket: 'austmart-2b349.appspot.com',
    iosBundleId: 'com.example.austmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXetSlXgyv-5hQ3AqAD5SgJ8BB3pmzz0s',
    appId: '1:666731394983:ios:fd7ded18a340cc343ba882',
    messagingSenderId: '666731394983',
    projectId: 'austmart-2b349',
    storageBucket: 'austmart-2b349.appspot.com',
    iosBundleId: 'com.example.austmart.RunnerTests',
  );
}
